US#479021 Control replicas in helm charts
opentext-idol/idol-containers-toolkit pull request #57
Opened 2024-05-09 16:00 UTC by hasan-mahmood-opentext

- Updated idol-library `_deployment.tpl` to get number of replicas from relevant values.yaml.
 - Updated all relevant charts to use default number of replicas (1).

2024-05-10 13:12 UTC, daniel-lau-mf reviewed
Please update idol-library-example-test as well.

2024-05-10 13:17 UTC, daniel-lau-mf requested changes
Mostly good - see feedback comments for some extra things to do.

2024-05-10 15:05 UTC, hasan-mahmood-opentext commented on helm/distributed-idol/values.yaml
> +  # replicas -- number of replica pods for this container (defaults to 1)
Is this only for this case or for the other charts as well?

2024-05-13 09:29 UTC, daniel-lau-mf commented on helm/distributed-idol/values.yaml
> +  # replicas -- number of replica pods for this container (defaults to 1)
Just this case.

2024-05-13 12:05 UTC, hasan-mahmood-opentext commented on helm/release/distributed-idol-0.9.0.tgz
yep, updated

2024-05-13 12:48 UTC, daniel-lau-mf approved these changes

2024-05-13 13:37 UTC, merged