Allow `envConfigMap` to take effect in idol-nifi
opentext-idol/idol-containers-toolkit pull request #68
Opened 2024-08-21 11:20 UTC by joe-wood-opentext

* This is supposed to work via `idol-library.aciserver.container.base.v1` but it isn't.
  * This allows the user to set environment variables via a config map and override the defaults in the `idol-nifi-env` [configMap](https://github.com/opentext-idol/idol-containers-toolkit/blob/main/helm/idol-nifi/templates/nifi/configmap.yaml).
  * Left out a chart version upgrade since it's a minor change, but happy to be convinced otherwise.
  * Comes with the additional bonus that users can easily specify `JAVA_HOME` if their container needs it, since it was removed in https://github.com/opentext-idol/idol-containers-toolkit/pull/67.
  * Needed to make LLaVA script configurable via environment variables.

2024-08-21 16:36 UTC, lewis-mackay-mf approved these changes

2024-08-22 15:45 UTC, daniel-lau-mf commented
Don't publish a new release for this - #69 folds more changes in.

2024-08-22 15:46 UTC, daniel-lau-mf requested changes
See my previous comment

2024-08-22 16:09 UTC, daniel-lau-mf approved these changes

2024-08-22 16:34 UTC, merged